import Navbar from "@/components/navbar/Navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { checkLoggedIn } from "@/lib/authenticate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const isLoggedIn = await checkLoggedIn()

  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center`}>
        <Navbar isLoggedIn={isLoggedIn} />
        {children}
      </body>
    </html>
  );
}
